Resources:
  PetTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: 'Pet'
      AttributeDefinitions:
        -
          AttributeName: 'Id'
          AttributeType: 'S'
      KeySchema:
        -
          AttributeName: 'Id'
          KeyType: 'HASH'
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  UserTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: 'User'
      AttributeDefinitions:
        -
          AttributeName: 'Id'
          AttributeType: 'S'
      KeySchema:
        -
          AttributeName: 'Id'
          KeyType: 'HASH'
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5


  InteractionsTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: 'Interactions'
      AttributeDefinitions:
        -
          AttributeName: 'id'
          AttributeType: 'S'
        -
          AttributeName: 'timestamp'
          AttributeType: 'S'
      KeySchema:
        -
          AttributeName: 'id'
          KeyType: 'HASH'
        -
          AttributeName: 'timestamp'
          KeyType: 'RANGE'
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
